### ISSUE TITLE
Store positions when no internet is avaiable?

### ISSUE THREAD

**Issue by connectnet** [tananaev/traccar-client-android#109] opened 2014-10-18 12:53 UTC
Is it possible to store the gps data in a local file at the mobile when no Internet connection is available and submit the data later?

**Comment by kdmax** [comment] 2015-02-05 13:21
Can you please update the source code to version 3.1 because i have the same problem after compiling the current version.

**Comment by tananaev** [comment] 2015-02-05 19:38
Source code contains all the latest changes.

**Comment by kdmax** [comment] 2015-02-05 20:40
Ok, but when i installed the app from Play Store it says that it is version 3.1, and when i build the code it is 3.0
Also version 3.0 still appears in build.gradle
https://github.com/tananaev/traccar-client-android/blob/master/traccar-client/build.gradle#L11

**Comment by tananaev** [comment] 2015-02-05 20:42
I forgot to commit version change, but everything else is there.

**Comment by jrischma** [comment] 2015-02-15 21:19
Hi , this change not solve the problem, when internet conection is lose so not store points.
only save 7 minutes.
anymore check ?

great job anton

**Comment by tananaev** [comment] 2015-02-15 21:26
I am planning to change protocol used by Traccar Client in near future to solve this problem.

**Comment by jrischma** [comment] 2015-02-15 21:30
i use other protocol, but app not send all data, is a problem memory maybe, memory is full so not store all data, only store 7 minutes at 15s inter.

**Comment by tananaev** [comment] 2015-02-15 21:40
What other protocol do you use? I am talking about completely new protocol over HTTP.

**Comment by jrischma** [comment] 2015-02-15 21:44
i modify u app for that sent same protocol extend but with imei and final tag # for split multiple data, so i can receive 1000 points at same time, but only receive 7 minutes, for example if travel was 60 min app only sent first 7 min , other 53 min (offline stored) is lose. for that i think is memory problem.

**Comment by tananaev** [comment] 2015-02-15 21:55
I doubt that there is a memory issue. When app runs out of memory it simply crashes, so you won't even get 7 minutes.

**Comment by jrischma** [comment] 2015-02-15 21:59
i receive multiple point from store data (offline period) but not all data only a segment, really, so not crash when conection is lose, crash is after but i dont know when or why.

**Comment by jrischma** [comment] 2015-02-15 22:18
but really its not a crash because app continue working, when recovers internet app sent to server a segment offline stored (7 min or 4 km) and sent new location (new location is when internet is recover) so not is a crash, only app cant stored all data but app can sent all data in memory.
maybe the problem is because app try reconect when lose internet.

**Comment by Anton-V-K** [comment] 2018-01-01 15:13
The version 5.5 stores positions data in offline mode, and doesn't loose this data after reboot, which is great. Even stopping/starting the service doesn't erase previously accumulated data (in offline mode), which is fantastic! :)
I guess, the issue may be closed...

**Comment by tananaev** [comment] 2018-01-01 20:33
This functionality has been available for a long time. Closing this issue.

**Closed by tananaev** 2018-01-01 20:33 UTC
